GH-2, GH-6: Add capability to pull parent data
singletoncoding/java-utils pull request #15
Opened 2018-06-26 17:21 UTC by bklager

Addresses GH-2 and Gh-6

2018-06-26 20:17 UTC, singletoncoding requested changes

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +const parsePOMFromString = (pomContents, findParent) => {
If this only takes in a function, it does limit your ability to pass in additional configuration.  Instead, I would make this take in an object called configuration that has a property expecting a function called "findParent".

This would allow us to add additional configuration in the future without having to worry about dealing with multiple permutations of arguments.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  var parentCoordinates = getCoordinatesFromNode(project.parent[0]);
change var to const.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  var parentGroupId = parentCoordinates.groupId.replace(/[.]/g, "/");
change var to const.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  var parentGroupId = parentCoordinates.groupId.replace(/[.]/g, "/");
While this definitely does what you want, I always question the readability of regular expressions.  They're usually pretty tough to understand, and there are multiple implementations across multiple languages.

I would prefer to just use split and replace...
```javascript
const parentGroupId = parentCoordinates.groupId.split('.').join('/');
```

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  if (findParent != undefined) {
I would actually move this resolution into the parsePOMFromString method.

```javascript
const parsePOMFromString = (pomContents, findParent) => {
  return new Promise(resolve => {
    return xml2js.parseString(pomContents, (err, result) => {
      resolve(result);
    });
  })
    .then(result => result.project)
    .then(data => buildJSONStructure(data, findParent ? findParent : defaultFetch));
};
```

The one part of this is that you now have to make the contract for the defaultFetch and the one provided be the same (basically the result of the method has to return a string that can be passed into the parsePOMFromString) method.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  const emptyPromise = new Promise(resolve => resolve(undefined));
It might make sense to make this a constant at the top of the file since we are referencing this in multiple places.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +const defaultFetch = (groupId, artifactId, version, repository) => {
repository should be repositories.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  var parentCoordinates = getCoordinatesFromNode(project.parent[0]);
Let's address this for all places in the code that it can be done.  This generally will also include arrays since you usually do not re-assign an array, but rather you push and remove data from them.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  var thePromises = [];
let's get this updated to be a bit more of a meaningful name.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  for (let i = 0; i < urls.length; i++) {
I would move the contents of this for loop into a separate function and just pass in the urls array.  It will help simplify the method and ensure that it's not doing multiple things (building the urls and performing get requests).

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +          if (error.response.status > 399 && error.response.status < 500)
Be very careful about using if and else conditions without curly braces around the code.  This can very easily introduce defects if someone adds something right after the if statement since it would cause your code to actually be executed outside of the if statement now.

If you are looking to condense some part of code, I would just suggest deferring to a separate function to handle it.  

```javascript
.catch(error => { 
  return handlePOMAxiosGetError(error);
});
```

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +        .catch(function(error) {
I would use arrow functions instead of declaring functions like this.  It's less noise to deal with.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +        project.repositories[0].repository
instead of parsing through the object structure again, I would just pass in the repositories from within the buildJSONStructure method.  This allows you to not have to pull from the xml content over and over.

Ideally the less places that we're traversing that object structure that doesn't really make a lot of sense (the whole array[0] thing, etc), the better.

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +const defaultFetch = (groupId, artifactId, version, repository) => {
I would change this to take an object that has properties for all of these things.  Given that this method will need to have the same contract as what we are asking the consumer to provide, we need to make sure that this contract can grow over time passively and nicely.

I think I would like to see the expected structure:

```js
{
  artifactCoordinates: {
    groupId: "a",
    artifactId: "b",
    version: "1.0.0"
  },
  repositories: []
}
```

2018-06-26 20:17 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +      promiseResults.filter(tooManyPromises => tooManyPromises != undefined)
Given that filter will iterate over all of the promises, it means that the function that you provide (the tooManyPromises => tooManyPromises != undefined) is only considering a single promise at a time.  For that reason (and that perhaps tooManyPromises doesn't really provide a lot of context to what we're doing here), let's go ahead and rename tooManyPromises to be something like "artifactRetrievalPromise"

2018-06-26 20:17 UTC, singletoncoding commented on src/test/pom-parser/pom-parser.test.js
> +          repository = pomContent.repositories[0];
This is happening in a few places.  You need to declare the variable at the same time or before you assign it.   (it is missing the const keyword at the beginning of this line).

There are a few places in the test where this is happening.

2018-06-26 20:17 UTC, singletoncoding commented on src/test/pom-parser/pom-parser.test.js
> +        var server = http.createServer(mock('./src/test/pom-parser/mocks')).listen(3001);
var should be const.

2018-06-26 20:17 UTC, singletoncoding commented on src/test/pom-parser/pom-parser.test.js
> +            parentPOM = pomContent.parentPom;
need to declare this as a variable before/during assignment.

2018-06-26 20:17 UTC, singletoncoding commented on src/test/pom-parser/pom-parser.test.js
> +    describe('Recursive Parent Pom Fetching', () => {
Should be a blank line before this line.

2018-06-26 20:17 UTC, singletoncoding commented on src/test/pom-parser/pom-parser.test.js
> +            assert.equal(parentPOM.parentPom.groupId, 'I am the overlord');
We should probably validate more information about the parent.

I'm fine with having simpler tests to ensure that we're handling the recursion correctly, but we likely should add a test to ensure that all of the expected properties are getting pulled in for the parent as well.

2018-06-27 14:20 UTC, bklager commented on src/main/pom-parser/pom-parser.js
> +  var thePromises = [];
But, if we leave it with that name then there's a line that says promise all the promises then promise results, and it entertains me

2018-06-27 14:25 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +  var thePromises = [];
Somehow I suspect you had a meaningful name for this variable and after seeing that opportunity you changed the name.

2018-07-03 17:27 UTC, singletoncoding requested changes

2018-07-03 17:27 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +        project.repositories[0].repository
Looks like this might need to be addressed still

2018-07-03 18:53 UTC, singletoncoding requested changes

2018-07-03 18:53 UTC, singletoncoding commented on src/main/pom-parser/pom-parser.js
> +const createConfigurationObject = (configuration) => {
talked offline, we can do attribute expansion to handle this.

2018-07-20 19:48 UTC, singletoncoding approved these changes

2018-07-20 19:48 UTC, merged